pipeline:
  identifier: Build_mukundbabbar_jhttp_1746533005300
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: mukundbabbar/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - type: Run
                identifier: build_java_app
                name: Build Java App
                spec:
                  shell: Sh
                  command: |-
                    echo "Welcome to Harness CI"
                    mvn -B package --file pom.xml
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
