pipeline:
  identifier: Build_mukundbabbar_jhttp_1746533005300
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: mukundbabbar/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Run
                  identifier: run_tests
                  name: Run Unit Tests
                  spec:
                    shell: Sh
                    command: |-
                      echo "Running tests..."
                      mvn test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Docker Build and Push
                  identifier: docker_push
                  spec:
                    connectorRef: MBPersonal
                    repo: mukundbabbar/jhttp
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
